print("Give me the first number: ")
num1 = int(input())
print("Give me the second number: ")
num2 = int(input())
print(num1, "+", num2, "=", num1 + num2)
print(num1, "-", num2, "=", num1 - num2)
print(num1, "/", num2, "=", num1 / num2)
print(num1, "*", num2, "=", num1 * num2)